### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by heipacker** [MOACChain/moac-core#35]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbd8d0b]

goroutine 83 [running]:
github.com/innowells/moac-vnode/mc/filters.(*EventSystem).eventLoop(0xc420080700)
	/home/ubuntu/moac-vnode/build/_workspace/src/github.com/innowells/moac-vnode/mc/filters/filter_system.go:429 +0x2eb
created by github.com/innowells/moac-vnode/mc/filters.NewEventSystem
	/home/ubuntu/moac-vnode/build/_workspace/src/github.com/innowells/moac-vnode/mc/filters/filter_system.go:112 +0x104

**Comment by mdranger** [comment]
Which version did you use? Did you connect any SCS with this vnode?

**Comment by mdranger** [comment]
Please update to Nuwa 1.0.0 and let us know if you still have trouble.
Thanks.
