### ISSUE TITLE
Cannot connect scs rpc in nuwa102

### ISSUE THREAD

**Issue by foreso-GitHub** [MOACChain/moac-core#44]
I connected scs rpc by following codes in go:

```
serverAddress := "localhost"
serverPort := "9545"
client, err := rpc.DialHTTP("tcp", serverAddress+":"+serverPort)
fmt.Println("err:", err, client) 
```

I start scs server by following commands:
```
scsserver -rpcaddr=0.0.0.0 -rpcport=9545
```

It works in pangu scs and nuwa 101.  But when I use the scs in nuwa102, error happened as following.
```
err: dial-http tcp localhost:9545: unexpected HTTP response: 404 Not Found <nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6ab33d]

goroutine 1 [running]:
net/rpc.(*Client).send(0x0, 0xc04212a0f0)
        C:/Go/src/net/rpc/client.go:72 +0x2d
net/rpc.(*Client).Go(0x0, 0x79f36a, 0x15, 0x74ae20, 0xc04200c3c0, 0x770ac0, 0xc04200a3e0, 0xc0420162a0, 0xc04200c3c0)
        C:/Go/src/net/rpc/client.go:311 +0xe5
net/rpc.(*Client).Call(0x0, 0x79f36a, 0x15, 0x74ae20, 0xc04200c3c0, 0x770ac0, 0xc04200a3e0, 0xc04212e040, 0xe)
        C:/Go/src/net/rpc/client.go:317 +0x9e
main.main()
        E:/work/Projects/go/codes/scs3.go:54 +0x2c2
```

Any suggestions?  Thanks!

**Comment by mdranger** [comment]
Please use nuwa SCS instead of pangu scs. Pangu scs is only for test on a private network.
