### ISSUE TITLE
too many msgs on testnet

### ISSUE THREAD

**Issue by wanpixiaozi** [MOACChain/moac-core#59]
I got below info on testnet vnode these days, my log would increase 100M bytes every day, who can solve this problem
```
ERROR[12-07|07:19:50.184] 813993:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.184] 1770498:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.196] 317211:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.196] 1329360:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.208] 1538153:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.219] 2405025:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.219] 1798677:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.229] 1745880:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.309] 2464173:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:50.431] 1883545:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.253] 1678671:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.253] 1177458:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.253] 1250201:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.253] 1478102:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.276] 2158324:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.276] 1497815:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.276] 1736334:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.276] 1919789:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.291] 2358471:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.291] 2415392:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.292] 1840894:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.292] 2464173:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.292] 1798677:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.292] 313007:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.292] 2405025:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.329] 813993:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.329] 1770498:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.330] 1489576:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.330] 806804:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.364] 1329360:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.364] 317211:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.364] 1538153:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.364] 1745880:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.365] 1883545:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
ERROR[12-07|07:19:51.663] 1917145:[test] [mc/network_relay] Too many msgs, too many msgs, too many msgs
INFO [12-07|07:19:52.717] 2468604:Imported new chain segment       blocks=1    txs=1    mgas=0.000   elapsed=6.861ms   mgasps=0.000   number=1469990 hash=0xc57361d2656f5ebcef85612ebb0fab587455fa3b158cf3e6119b61d2bbc0c0f7
INFO [12-07|07:19:52.718] 41:Commit new mining work number=1469991 txs=1 uncles=0 elapsed=1.131ms
INFO [12-07|07:19:55.417] 2468755:Imported new chain segment       blocks=1    txs=1    mgas=0.000   elapsed=6.769ms   mgasp
```
besides, my vnode crashed at this point
```
INFO [12-07|07:21:17.903] 41:Commit new mining work number=1469999 txs=1 uncles=0 elapsed=909.791µs
INFO [12-07|07:21:36.032] 2471301:Imported new chain segment       blocks=1    txs=1    mgas=0.000   elapsed=5.940ms   mgasps=0.000   number=1469999 hash=0x7de12d22b3c324a550b2a33d02de55b30aed31a2e7135751c27928d557b404e4
INFO [12-07|07:21:36.033] 41:Commit new mining work number=1470000 txs=1 uncles=0 elapsed=876.234µs
unexpected fault address 0x7ff6b717ab08
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7ff6b717ab08 pc=0x463efc]

goroutine 2470847 [running]:
runtime.throw(0xfdc6bf, 0x5)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc001b01a88 sp=0xc001b01a58 pc=0x4328e2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc001b01ad8 sp=0xc001b01a88 pc=0x4489b5
runtime.memmove(0xc01c549200, 0x7ff6b717ab08, 0x40)
        /usr/local/go/src/runtime/memmove_amd64.s:184 +0x15c fp=0xc001b01ae0 sp=0xc001b01ad8 pc=0x463efc
github.com/innowells/moac-vnode/consensus/ethash.hashimoto(0xc001b01de8, 0x20, 0x20, 0x361b2544e59213f7, 0x57fffc80, 0xc001b01cc8, 0x50bee3, 0xc001b01ce8, 0x50bb50, 0xc00dafce00, ...)
        /ext-go/2/src/github.com/innowells/moac-vnode/consensus/ethash/algorithm.go:312 +0x300 fp=0xc001b01c68 sp=0xc001b01ae0 pc=0xaa2c10
@                                                                                             
```

**Comment by mdranger** [comment]
Currently we setup a limit of SCS Messages for a VNODE to receive between the blocks on MotherChain. When the MotherChain has a slow block, the number of messages sent from SCSs can exceed the limit and generated these errors. We are working on this and will publish a fix soon.
Your VNODE crashed with the same mistake as before. You don't need to do mining on the testnet.
